// <auto-generated />
using System;
using GruopEventPage.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GruopEventPage.Migrations.SqliteMigrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200503122529_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("GruopEventPage.Entities.EventForm", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateEvent")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescEvent")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEvent")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberPlacesEvent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumbersOfCurrentParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Organizer")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceEvent")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeEvent")
                        .HasColumnType("TEXT");

                    b.HasKey("EventID");

                    b.ToTable("EventFormFootball");
                });

            modelBuilder.Entity("GruopEventPage.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
