// <auto-generated />
using System;
using GruopEventPage.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GruopEventPage.Migrations.SqliteMigrations
{
	[DbContext(typeof(DataContext))]
	partial class SqliteDataContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "3.1.2");

			modelBuilder.Entity("GruopEventPage.Entities.User", b =>
				{
					b.Property<int>("UserID")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("FirstName")
						.HasColumnType("TEXT");

					b.Property<string>("LastName")
						.HasColumnType("TEXT");

					b.Property<byte[]>("PasswordHash")
						.HasColumnType("BLOB");

					b.Property<byte[]>("PasswordSalt")
						.HasColumnType("BLOB");

					b.Property<string>("Role")
						.HasColumnType("TEXT");

					b.Property<string>("Username")
						.HasColumnType("TEXT");

					b.HasKey("UserID");

					b.ToTable("Users");
				});
#pragma warning restore 612, 618
		}
	}
}
